---
- hosts: ubuntu
  become: yes

  tasks:
  - name: Fetch variables
    include_vars: "../vars//{{ ansible_os_family }}.yml"

  - name: Install Java JRE on Ubuntu
    apt: name={{ jre_package_name }} state=installed
    environment:
      _JAVA_OPTIONS: "{{ java_options }}"
    when: ansible_os_family == 'Debian'

  - name: Install Java JDK on Ubuntu
    apt:
      name: "{{ jdk_package_name }}"
      state: installed
    when: ansible_os_family == 'Debian'

  - name: Add Jenkins repository key on Ubuntu
    apt_key:
      url: "{{ jenkins_repo_key_url }}"
      state: present
    when: ansible_os_family == 'Debian'

  - name: Add Jenkins repository on Ubuntu
    apt_repository:
      repo: "{{ jenkins_repo }}"
      state: present
    when: ansible_os_family == 'Debian'

  - name: Install Jenkins
    apt: name={{ jenkins_package_name }} state=installed update_cache=yes
    notify:
    - start jenkins
    when: ansible_os_family == 'Debian'
